//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dealer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Automovil
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Automovil()
        {
            this.Compras = new HashSet<Compra>();
            this.Detalles = new HashSet<Detalle>();
            this.Detalles1 = new HashSet<Detalle>();
        }
    
        public int ID_Auto { get; set; }
        public int ID_Marca { get; set; }
        public string Modelo { get; set; }
        public int Año_Fabricacion { get; set; }
        public int ID_Tipo { get; set; }
        public int ID_CantPasajeros { get; set; }
        public int ID_TipoTrans { get; set; }
        public decimal Precio { get; set; }
        public string Tipo_Moneda { get; set; }
    
        public virtual Cant_Pasajeros Cant_Pasajeros { get; set; }
        public virtual Marca Marca { get; set; }
        public virtual Tipo_Automovil Tipo_Automovil { get; set; }
        public virtual Tipo_Trans Tipo_Trans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Compra> Compras { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detalle> Detalles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detalle> Detalles1 { get; set; }
    }
}
