//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dealer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compra
    {
        public int ID_Compra { get; set; }
        public string ID_User { get; set; }
        public int ID_Empleado { get; set; }
        public int ID_Auto { get; set; }
        public int Cantidad { get; set; }
        public decimal Total { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Automovil Automovil { get; set; }
        public virtual Empleado Empleado { get; set; }
    }
}
