//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dealer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DealersEntities : DbContext
    {
        public DealersEntities()
            : base("name=DealersEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<Automovil> Automovils { get; set; }
        public virtual DbSet<Cant_Pasajeros> Cant_Pasajeros { get; set; }
        public virtual DbSet<Compra> Compras { get; set; }
        public virtual DbSet<Condicion> Condicions { get; set; }
        public virtual DbSet<Empleado> Empleados { get; set; }
        public virtual DbSet<Marca> Marcas { get; set; }
        public virtual DbSet<Tipo_Automovil> Tipo_Automovil { get; set; }
        public virtual DbSet<Tipo_Trans> Tipo_Trans { get; set; }
    }
}
