//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dealer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ubicacion
    {
        public int ID_Ubicacion { get; set; }
        public int ID_Sucursal { get; set; }
        public int ID_Auto { get; set; }
    
        public virtual Automovil Automovil { get; set; }
        public virtual Sucursal Sucursal { get; set; }
    }
}
